CREATE TABLE CAT_RAZA 
(
  ID_RAZA NUMBER(*, 0) NOT NULL
, DESCRIPCION VARCHAR2(50 BYTE) 
, CONSTRAINT CAT_RAZA_PK PRIMARY KEY 
  (
    ID_RAZA 
  )
  ENABLE 
);

CREATE TABLE CAT_COLOR 
(
  ID_COLOR NUMBER(*, 0) NOT NULL 
, DESCRIPCION VARCHAR2(50 BYTE) 
, CONSTRAINT CAT_COLOR_PK PRIMARY KEY 
  (
    ID_COLOR 
  )
  ENABLE 
);

CREATE TABLE CAT_TAMANIO 
(
  ID_TAMANIO NUMBER(*, 0) NOT NULL 
, DESCRIPCION VARCHAR2(50 BYTE) 
, CONSTRAINT CAT_COLOR_PK PRIMARY KEY 
  (
    ID_TAMANIO 
  )
  ENABLE 
);

CREATE TABLE CAT_SEX 
(
  ID_SEX NUMBER(*, 0) NOT NULL
, DESCRIPCION VARCHAR2(20 BYTE) 
, CONSTRAINT CAT_SEX_PK PRIMARY KEY 
  (
    ID_SEX 
  )
  ENABLE 
);

CREATE TABLE CAT_SINTOMAS 
(
  ID_SINTOMAS NUMBER(*, 0) NOT NULL 
, DESCRIPCION VARCHAR2(100 BYTE) 
, CONSTRAINT CAT_SINTOMAS_PK PRIMARY KEY 
  (
    ID_SINTOMAS 
  )
);


CREATE TABLE CAT_USUARIO
(	
  ID_USUARIO NUMBER(*,0) NOT NULL, 
  NOMBRE 	 VARCHAR2(30 BYTE), 
  AP_PATERNO VARCHAR2(50 BYTE), 
  AP_MATERNO VARCHAR2(50 BYTE),
  CONSTRAINT CAT_USUARIO_PK PRIMARY KEY
  (
	ID_USUARIO
  )
) 

CREATE TABLE VISITAS
(	
  ID_VISITA      NUMBER(*,0) NOT NULL, 
  ID_SINTOMAS    NUMBER(*, 0),
  DIAGNOSTICO 	 VARCHAR2(300 BYTE), 
  FECHA			 DATE, 
  ID_USUARIO     NUMBER(*,0),
  CONSTRAINT CAT_VISITAS_PK PRIMARY KEY
  (
	ID_VISITA
  )
) 


CREATE TABLE MASCOTA
(	
  ID_MASCOTA     NUMBER(*,0) NOT NULL, 
  NOMBRE 	     VARCHAR2(30 BYTE),
  ID_RAZA        NUMBER(*,0), 
  ID_COLOR       NUMBER(*,0), 
  ID_TAMANIO     NUMBER(*,0),
  EDAD			 NUMBER(*,0),
  ID_SEX         NUMBER(*,0),
  ID_USUARIO     NUMBER(*,0),
  CONSTRAINT CAT_MASCOTA_PK PRIMARY KEY
  (
	ID_MASCOTA
  )
) 


CREATE SEQUENCE RAZA_SEQUENCE INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE COLOR_SEQUENCE INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE TAMANIO_SEQUENCE INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEX_SEQUENCE INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SINTOMAS_SEQUENCE INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE USUARIO_SEQUENCE INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE VISITA_SEQUENCE INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE MASCOTA_SEQUENCE INCREMENT BY 1 START WITH 1;


